// C:\xampp\htdocs\InmobiliariaRural\src\config\endpoints.js
import API_CONFIG from './api.config';

// Función para construir URLs completas
const buildUrl = (endpoint) => `${API_CONFIG.BASE_URL}${endpoint}`;

// Endpoints de admin
export const ADMIN_ENDPOINTS = {
  LOGIN: buildUrl(API_CONFIG.ADMIN.LOGIN),
  LOGOUT: buildUrl(API_CONFIG.ADMIN.LOGOUT),
  DASHBOARD: buildUrl(API_CONFIG.ADMIN.DASHBOARD),
  CHECK_SESSION: buildUrl(API_CONFIG.ADMIN.CHECK_SESSION),
};

// Endpoints de consultas
export const CONSULTAS_ENDPOINTS = {
  CREAR: buildUrl(API_CONFIG.CONSULTAS.CREAR),
  LISTAR: buildUrl(API_CONFIG.CONSULTAS.LISTAR),
  ELIMINAR: buildUrl(API_CONFIG.CONSULTAS.ELIMINAR),
  ULTIMAS: buildUrl(API_CONFIG.CONSULTAS.ULTIMAS),
};

// Endpoints de propiedades
export const PROPIEDADES_ENDPOINTS = {
  LISTAR: buildUrl(API_CONFIG.PROPIEDADES.LISTAR), // Admin
  LISTAR_PUBLIC: buildUrl(API_CONFIG.PROPIEDADES.LISTAR_PUBLIC), // Público
  CREAR: buildUrl(API_CONFIG.PROPIEDADES.CREAR),
  MODIFICAR: buildUrl(API_CONFIG.PROPIEDADES.MODIFICAR),
  ELIMINAR: buildUrl(API_CONFIG.PROPIEDADES.ELIMINAR),
  DETALLE: buildUrl(API_CONFIG.PROPIEDADES.DETALLE),
  ESTADISTICAS: buildUrl(API_CONFIG.PROPIEDADES.ESTADISTICAS),
  DESTACADAS: buildUrl(API_CONFIG.PROPIEDADES.DESTACADAS),
  ELIMINAR_IMAGEN: buildUrl(API_CONFIG.PROPIEDADES.ELIMINAR_IMAGEN),
};

// Endpoints de servicios
export const SERVICIOS_ENDPOINTS = {
  LISTAR: buildUrl(API_CONFIG.SERVICIOS.LISTAR),
  CREAR: buildUrl(API_CONFIG.SERVICIOS.CREAR),
  MODIFICAR: buildUrl(API_CONFIG.SERVICIOS.MODIFICAR),
  ELIMINAR: buildUrl(API_CONFIG.SERVICIOS.ELIMINAR),
};

// Endpoints de tipos de campos
export const TIPOS_CAMPOS_ENDPOINTS = {
  LISTAR: buildUrl(API_CONFIG.TIPOS_CAMPOS.LISTAR),
  CREAR: buildUrl(API_CONFIG.TIPOS_CAMPOS.CREAR),
  MODIFICAR: buildUrl(API_CONFIG.TIPOS_CAMPOS.MODIFICAR),
  ELIMINAR: buildUrl(API_CONFIG.TIPOS_CAMPOS.ELIMINAR),
};

// Endpoints de utilidades
export const UTILS_ENDPOINTS = {
  DOLAR: buildUrl(API_CONFIG.UTILS.DOLAR),
  NOTIFICACIONES: buildUrl(API_CONFIG.UTILS.NOTIFICACIONES),
};

// Endpoints agrupados para fácil acceso
const ENDPOINTS = {
  ADMIN: ADMIN_ENDPOINTS,
  CONSULTAS: CONSULTAS_ENDPOINTS,
  PROPIEDADES: PROPIEDADES_ENDPOINTS,
  SERVICIOS: SERVICIOS_ENDPOINTS,
  TIPOS_CAMPOS: TIPOS_CAMPOS_ENDPOINTS,
  UTILS: UTILS_ENDPOINTS,
  // URL base
  BASE_URL: API_CONFIG.BASE_URL,
  // Opciones por defecto
  DEFAULT_OPTIONS: API_CONFIG.DEFAULT_OPTIONS
};

export default ENDPOINTS;